// src/views/Battle.vue
<template>
  <h2>Battle</h2>
  <div class="battle-page">
    <div v-if="loading" class="loading">
      <p>Loading...</p>
    </div>
    <div v-else>
      <SelectPetComponent v-if="cs === 'SELECT_PET'" :m="battle?.m" :os="battle?.os" @pokemon-selected="handlePokemonSelected"/>
      <BattleComponent v-else-if="cs === 'SELECT_ACTION'" :battle="battle" @action-selected="handleActionSelected"/>
      <BattleEndComponent v-else-if="cs === 'END_BATTLE'" :battle="battle"/>
    </div>
  </div>
</template>

<script>
import BattleService from "../services/BattleService"; // Updated to import BattleService
import SelectPetComponent from "../components/battle/SelectPetComponent.vue"
import BattleComponent from "../components/battle/BattleComponent.vue"
import eventBus from "@/eventBus.js";
import BattleEndComponent from "@/components/battle/BattleEndComponent.vue";
import UXService from "@/services/UXService.js";

export default {
  components: {
    BattleEndComponent,
    SelectPetComponent,
    BattleComponent,
  },
  props: {
    ci: {type: String, required: true},
    ai: {type: Number, required: true},
    t: {type: String, required: true},
  },
  data() {
    return {
      loading: true,
      cs: null, // 'SELECT_PET' or 'IN_BATTLE'
      battle: null, // Holds the data received from the API
    };
  },
  async created() {
    // Fetch which Petster to battle
    eventBus.on('bd', (bd) => {
      this.ci = bd.ci;
      this.ai = bd.ai;
      this.t = bd.t;
      this.initiateBattle();
    });

  },
  methods: {
    async initiateBattle() {
      try {
        // Fetch initial battle data from API and process state
        const response = await BattleService.initiateBattle(this.t,{cs: null, ci: this.ci, ai: this.ai}); // Changed to use BattleService
        this.processBattleResponse(response);
      } catch (error) {
        UXService.notify("an error occurred while starting the battle.", error)
      } finally {
        this.loading = false;
      }
    },
    processBattleResponse(response) {
      this.battle = response;
      if (response.ns === 1 || response.ns === 6) {
        this.cs = "SELECT_PET"; // Show SelectPetComponent
      } else if (response.ns === 2 || response.ns === 7) {
        this.cs = "SELECT_ACTION"; // Show BattleComponent
      } else if (response.ns === 5 || response.ns === 9) {
        alert("Battle ended");
        this.cs = "END_BATTLE"; // Show BattleEndComponent
      } else {
        UXService.warn("Unexpected battle state: " + response.ns);
      }
    },
    async handlePokemonSelected(pokemon) {
      try {
        this.loading = true;
        const response = await BattleService.continueBattle(this.t, {cs: 6, oi: pokemon.i}); // Changed to use BattleService
        console.log(response);
        eventBus.emit('battle-update', response.ts);
        this.processBattleResponse(response);
      } catch (error) {
        UXService.notify("an error occurred while selecting the pokemon.", error)
      } finally {
        this.loading = false;
      }
    },
    async handleActionSelected(action) {
      try {
        this.loading = true;
        const response = await BattleService.continueBattle(this.t, {cs: 7, oi: action.item}); // Changed to use BattleService
        console.log(response);
        eventBus.emit('battle-update', response.ts);
        this.processBattleResponse(response);
      } catch (error) {
        UXService.notify("an error occurred while performing the action.", error)
      } finally {
        this.loading = false;
      }
    },
  },
};
</script>

<style scoped>
.battle-page {
  margin: 20px;
}

.loading {
  font-size: 18px;
  color: #555;
}
</style>

// src/app/battle/page.tsx
'use client';

import { useState, useEffect } from 'react';
import BattleService from "@/services/BattleService";
import UXService from "@/services/UXService";
import eventBus from "@/eventBus";
import SelectPet from "@/components/battle/SelectPet";
import BattleMain from "@/components/battle/BattleMain";
import BattleEnd from "@/components/battle/BattleEnd";

export default function BattlePage() {
    const [loading, setLoading] = useState(true);
    const [cs, setCs] = useState<string | null>(null); // 'SELECT_PET', 'SELECT_ACTION', 'END_BATTLE'
    const [battle, setBattle] = useState<any>(null);
    const [ci, setCi] = useState<string | null>(null);
    const [ai, setAi] = useState<number | null>(null);
    const [t, setT] = useState<string | null>(null);

    useEffect(() => {
        console.log("Battle created");

        const initiateBattle = async (bd: any) => {
            setCi(bd.ci);
            setAi(bd.ai);
            setT(bd.t);
            setLoading(true);
            console.log("Initiating battle");

            try {
                const response = await BattleService.initiateBattle(bd.t, { cs: null, ci: bd.ci, ai: bd.ai });
                processBattleResponse(response);
            } catch (error) {
                UXService.error("an error occurred while starting the battle.", error);
            } finally {
                setLoading(false);
            }
        };

        eventBus.on('bd', initiateBattle);

        return () => {
            eventBus.off('bd', initiateBattle);
        };
    }, []);

    const processBattleResponse = (response: any) => {
        setBattle(response);
        if (response.ns === 1 || response.ns === 6) {
            setCs("SELECT_PET");
        } else if (response.ns === 2 || response.ns === 7) {
            setCs("SELECT_ACTION");
        } else if (response.ns === 5 || response.ns === 9) {
            setCs("END_BATTLE");
        } else {
            UXService.warn("Unexpected battle state: " + response.ns);
        }
    };

    const handlePokemonSelected = async (pokemon: any) => {
        if (!t) return;
        try {
            setLoading(true);
            const response = await BattleService.continueBattle(t, { cs: 6, oi: pokemon.i });
            console.log(response);
            eventBus.emit('battle-update', response.ts);
            processBattleResponse(response);
        } catch (error) {
            UXService.error("an error occurred while selecting the pokemon.", error);
        } finally {
            setLoading(false);
        }
    };

    const handleActionSelected = async (action: any) => {
        if (!t) return;
        try {
            setLoading(true);
            const response = await BattleService.continueBattle(t, { cs: 7, oi: action.item });
            console.log(response);
            eventBus.emit('battle-update', response.ts);
            processBattleResponse(response);
        } catch (error) {
            UXService.error("an error occurred while performing the action.", error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div>
            <h2 className="text-2xl font-bold mb-4">Battle</h2>
            {loading ? (
                <div className="text-[18px] text-[#555]">Loading...</div>
            ) : (
                <div>
                    {cs === 'SELECT_PET' && battle && (
                        <SelectPet
                            m={battle.m}
                            os={battle.os}
                            onPokemonSelected={handlePokemonSelected}
                        />
                    )}
                    {cs === 'SELECT_ACTION' && battle && (
                        <BattleMain
                            battle={battle}
                            onActionSelected={handleActionSelected}
                        />
                    )}
                    {cs === 'END_BATTLE' && battle && t && (
                        <BattleEnd
                            battle={battle}
                            t={t}
                        />
                    )}
                    {!cs && !loading && <div>Waiting for battle to start...</div>}
                </div>
            )}
        </div>
    );
}
