// src/app/gyms/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import ApiService from '@/services/ApiService';
import UXService from '@/services/UXService';
import ImageService from '@/services/ImageService';
import eventBus from '@/eventBus';

const typeStyles: Record<string, string> = {
    Normal: "border-[#a8a878] bg-[#f8f8f0]",
    Fire: "border-[#f08030] bg-[#fddfdf]",
    Water: "border-[#6890f0] bg-[#def3fd]",
    Grass: "border-[#78c850] bg-[#e0f8d0]",
    Electric: "border-[#f8d030] bg-[#fff8dc]",
    Ice: "border-[#98d8d8] bg-[#f0ffff]",
    Fighting: "border-[#c03028] bg-[#fdd5d5]",
    Poison: "border-[#a040a0] bg-[#f8d4f8]",
    Ground: "border-[#e0c068] bg-[#f8e0b8]",
    Flying: "border-[#a890f0] bg-[#eef1fa]",
    Psychic: "border-[#f85888] bg-[#ffe6ed]",
    Bug: "border-[#a8b820] bg-[#f8ffd0]",
    Rock: "border-[#b8a038] bg-[#f8e8d0]",
    Ghost: "border-[#705898] bg-[#e8d8f8]",
    Dragon: "border-[#7038f8] bg-[#ece0ff]",
    Dark: "border-[#705848] bg-[#e8d8c8]",
    Steel: "border-[#b8b8d0] bg-[#f0f0f8]",
    Fairy: "border-[#ee99ac] bg-[#ffe3f3]",
};

export default function GymsPage() {
    const [gyms, setGyms] = useState<any[]>([]);
    const router = useRouter();

    useEffect(() => {
        async function fetchGyms() {
            try {
                const data = await ApiService.makeRequest("/gym");
                setGyms(data);
            } catch (error) {
                UXService.error("an error occurred while fetching gyms.", error);
            }
        }
        fetchGyms();
    }, []);

    const getGymClass = (type: string) => {
        return typeStyles[type] || "border-[#ccc] bg-[#f9f9f9]";
    };

    const startGymBattle = (gi: string) => {
        console.log('startGymBattle called with:', gi);
        setTimeout(() => {
            console.log("emitting");
            eventBus.emit("bd", { ci: gi, ai: 8, t: 'trainer' });
        }, 1000);

        router.push("/battle");
    };

    return (
        <div>
            <h2 className="text-base md:text-xl font-bold mb-2 md:mb-3">Gyms</h2>
            <div className="flex flex-wrap gap-2 md:gap-3 mt-2 md:mt-3 flex-col md:flex-row">
                {gyms.map((gym) => (
                    <div
                        key={gym.i}
                        className={`flex-1 min-w-[250px] md:min-w-[300px] border-2 rounded-lg overflow-hidden shadow-md cursor-pointer ${getGymClass(gym.t)}`}
                        onClick={() => startGymBattle(gym.gi)}
                    >
                        <div className="flex items-center justify-between p-2 md:p-3">
                            <div className="flex flex-col items-center text-center flex-1 p-2">
                                <img
                                    src={ImageService.getImageURLForGymMedal(gym.m)}
                                    alt={gym.m}
                                    className="w-12 h-12 md:w-16 md:h-16 object-cover mb-2"
                                />
                                <div className="text-center">
                                    <h3 className="m-0 text-xs md:text-sm text-[#333] font-bold">{gym.m} Badge</h3>
                                    <br />
                                    <h4 className="m-1 md:m-2 text-[#666] text-xs">{gym.l}</h4>
                                    <h5 className="m-1 md:m-2 text-[#666] text-xs">{gym.g}</h5>
                                </div>
                            </div>
                            <div className="flex-1 flex items-center justify-center p-2">
                                <img
                                    src={ImageService.getImageURLForGymMaster(gym.g)}
                                    alt={gym.g}
                                    className="w-auto h-35 md:h-40 lg:h-40 object-cover rounded-lg"
                                />
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}

// src/views/Gyms.vue
<template>
  <div class="gyms">
    <h2>Gyms</h2>
    <div class="gym-container">
      <div v-for="gym in gyms" :key="gym.i" class="gym-card" :class="getGymClass(gym.t)">
        <a @click="startGymBattle(gym.gi)" class="gym-link">
          <div class="gym-content">
            <div class="gym-left">
              <img :src="getGymMedalImage(gym.m)" :alt="gym.m" class="badge-image"/>
              <div class="gym-details">
                <h3>{{ gym.l }}</h3>
                <p>{{ gym.m }} Badge</p>
              </div>
            </div>
            <div class="gym-right">
              <img :src="getGymMasterImage(gym.g)" :alt="gym.g" class="leader-image"/>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</template>

<script>
import ApiService from "@/services/ApiService";
import UXService from "@/services/UXService.js";
import ImageService from "@/services/ImageService.js";
import eventBus from "@/eventBus.js";

export default {
  name: "Gyms",
  data() {
    return {
      gyms: [],
      typeStyles: {
        Normal: "normal-style",
        Fire: "fire-style",
        Water: "water-style",
        Grass: "grass-style",
        Electric: "electric-style",
        Ice: "ice-style",
        Fighting: "fighting-style",
        Poison: "poison-style",
        Ground: "ground-style",
        Flying: "flying-style",
        Psychic: "psychic-style",
        Bug: "bug-style",
        Rock: "rock-style",
        Ghost: "ghost-style",
        Dragon: "dragon-style",
        Dark: "dark-style",
        Steel: "steel-style",
        Fairy: "fairy-style",
      },
    };
  },
  methods: {
    getGymClass(type) {
      return this.typeStyles[type] || "default-style";
    },
    getGymMedalImage(name) {
      return ImageService.getImageURLForGymMedal(name);
    },
    getGymMasterImage(name) {
      return ImageService.getImageURLForGymMaster(name);
    },
    startGymBattle(gi) {
      console.log('startGymBattle called with:', gi); // Debugging
      setTimeout(() => {
        console.log("emitting")
        eventBus.emit("bd", {ci: gi, ai: 8, t: 'trainer'}); //TODO: Set appropriate ai for later
      }, 1000);

      this.$router.push({ name: "Battle" });
    }
  },
  async created() {
    try {
      this.gyms = await ApiService.makeRequest("/gym");
      console.log(this.gyms);
    } catch (error) {
      UXService.notify("an error occurred while fetching gyms.", error);
    }
  },
};
</script>

<style scoped>
.gym-container {
  margin-top: 15px;
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
}

.gym-card {
  flex: 1 1 calc(50% - 16px);
  border: 2px solid;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.gym-link {
  text-decoration: none;
  color: inherit;
  display: block;
  padding: 10px;
}

.gym-content {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.gym-left {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  flex: 1;
}

.gym-right {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

.badge-image {
  width: 70px;
  height: 70px;
  object-fit: cover;
  border-radius: 50%;
  margin-bottom: 10px;
}

.gym-details {
  text-align: center;
}

.gym-details h3 {
  margin: 0;
  font-size: 16px;
  color: #333;
}

.gym-details p {
  margin: 8px 0 0;
  color: #666;
  font-size: 14px;
}

.leader-image {
  width: auto;
  height: 180px; /* Slightly larger height for Gym Master */
  object-fit: cover;
  border-radius: 8px;
}

.gym-content .gym-left,
.gym-content .gym-right {
  padding: 10px;
}

/* Type-Specific Styles */
.normal-style {
  border-color: #a8a878;
  background-color: #f8f8f0;
}

.fire-style {
  border-color: #f08030;
  background-color: #fddfdf;
}

.water-style {
  border-color: #6890f0;
  background-color: #def3fd;
}

.grass-style {
  border-color: #78c850;
  background-color: #e0f8d0;
}

.electric-style {
  border-color: #f8d030;
  background-color: #fff8dc;
}

.ice-style {
  border-color: #98d8d8;
  background-color: #f0ffff;
}

.fighting-style {
  border-color: #c03028;
  background-color: #fdd5d5;
}

.poison-style {
  border-color: #a040a0;
  background-color: #f8d4f8;
}

.ground-style {
  border-color: #e0c068;
  background-color: #f8e0b8;
}

.flying-style {
  border-color: #a890f0;
  background-color: #eef1fa;
}

.psychic-style {
  border-color: #f85888;
  background-color: #ffe6ed;
}

.bug-style {
  border-color: #a8b820;
  background-color: #f8ffd0;
}

.rock-style {
  border-color: #b8a038;
  background-color: #f8e8d0;
}

.ghost-style {
  border-color: #705898;
  background-color: #e8d8f8;
}

.dragon-style {
  border-color: #7038f8;
  background-color: #ece0ff;
}

.dark-style {
  border-color: #705848;
  background-color: #e8d8c8;
}

.steel-style {
  border-color: #b8b8d0;
  background-color: #f0f0f8;
}

.fairy-style {
  border-color: #ee99ac;
  background-color: #ffe3f3;
}

/* Default Fallback Style */
.default-style {
  border-color: #ccc;
  background-color: #f9f9f9;
}
</style>
