// _legacy_vue/src/components/presets/TypePreset.vue
<template>
  <div class="type-squares">
    <div v-for="(type, i) in types" :key="i" :style="{ backgroundColor: TypeService.getTypeColor(type) }" class="type-square" :title="type">{{ type }}</div>
  </div>
</template>

<script setup>
import TypeService from "@/services/TypeService.js";
import {onMounted, ref} from "vue";

// Reactive States / Props
const types = ref([]);

// Lifecycle hook
onMounted(async () => {
  console.log("TypePreset mounted");
});

</script>

<style scoped>

</style>

// src/components/presets/TypePreset.tsx
import TypeService from "@/services/TypeService";

interface TypePresetProps {
    types: string[];
}

export default function TypePreset({ types }: TypePresetProps) {
    return (
        <div className="flex gap-[5px]">
            {types.map((type, i) => (
                <div
                    key={i}
                    className="text-white text-[13px] w-[45px] py-[5px] px-[9px] rounded-[8px] inline-block text-center"
                    style={{ backgroundColor: TypeService.getTypeColor(type) }}
                    title={type}
                >
                    {type}
                </div>
            ))}
        </div>
    );
}
