// src/components/info/PetInfoComponent.tsx
import { useState, useEffect } from 'react';
import PetsterService from "@/services/PetsterService";

interface PetInfoComponentProps {
    id: string | number;
    pet?: any;
}

export default function PetInfoComponent({ id, pet }: PetInfoComponentProps) {
    const [p, setP] = useState<any>(pet || {});

    useEffect(() => {
        async function loadData() {
            if (pet) {
                setP(pet);
            } else {
                try {
                    const data = await PetsterService.loadPetInfo(id);
                    setP(data);
                } catch (error) {
                    console.error("Error loading Pet info:", error);
                }
            }
        }
        if (id || pet) {
            loadData();
        }
    }, [id, pet]);

    if (!p.n && !p.i) return <div>Loading...</div>;

    return (
        <div>
            <h3 className="font-bold">Details of {id}</h3>
            <h3 className="font-bold">{p.n}</h3>
            <br />
            {/* Add more details as needed based on API response structure */}
        </div>
    );
}

// _legacy_vue/src/components/info/PetInfoComponent.vue
<template>
  <h3>Details of {{id}}</h3>
  <h3>{{ p.n }}</h3>
  <br>


</template>

<script setup>
import {reactive, watchEffect} from "vue";
import PetsterService from "@/services/PetsterService.js";
import TypeService from "@/services/TypeService.js";
import ImageService from "@/services/ImageService.js";

// Props
const props = defineProps({
  id: {
    type: Number,
    required: true
  },
  pet: {
    type: Object,
    required: false
  }
});

// Reactive state for Pokémon data
const p = reactive({});

// Fetch Pokemon info whenever `props.id` changes
watchEffect(async () => {
  try {
    const data = (props.pet !== undefined) ? props.pet : await PetsterService.loadPetInfo(props.id);
    Object.assign(p, data); // Update the reactive object with the fetched data
  } catch (error) {
    console.error("Error loading Pokemon info:", error);
  }
});
</script>

<style scoped>

</style>
