// src/components/map/JoystickComponent.vue
<template>
  <h2>Map Controls</h2>
  <p class="instructions">Use the arrow keys, touch, or drag the joystick to move the map.</p>
  <br/>
  <div class="joystick-container" @keydown="handleKeyPress" @touchstart="handleTouchStart" @touchmove="handleTouchMove" @touchend="handleTouchEnd" tabindex="0" ref="joystick">
    <div class="joystick">
      <div class="joystick-base" ref="joystickBase">
        <div
            class="joystick-knob"
            :style="{ left: `${knobPosition.x}px`, top: `${knobPosition.y}px` }"
            @mousedown="startDrag"
            @mouseup="endDrag"
            @mousemove="drag"
        ></div>
      </div>
    </div>
  </div>
</template>

<script>
import { throttle } from 'lodash';
import eventBus from "@/eventBus.js";

export default {
  data() {
    return {
      dragging: false,
      knobPosition: { x: 50, y: 50 }, // Start at center
      center: { x: 50, y: 50 }, // Initial center in percentage
      radius: 50, // Radius in percentage
      lastDirection: '', // To prevent redundant emits
      fireEventInterval: null, // Interval for continuous firing
    };
  },
  mounted() {
    const rect = this.$refs.joystickBase.getBoundingClientRect();
    this.center = { x: rect.width / 2, y: rect.height / 2 };

    // Attach global keydown and keyup listeners
    window.addEventListener('keydown', this.handleKeyPress);
    window.addEventListener('keyup', this.stopContinuousEvents);

    // Throttle direction emission
    this.emitDirectionThrottled = throttle(this.emitDirection, 200);
  },
  beforeUnmount() {
    window.removeEventListener('keydown', this.handleKeyPress);
    window.removeEventListener('keyup', this.stopContinuousEvents);
  },
  methods: {
    emitDirection(x, y) {
      let direction = '';

      if (y > 0) direction = 'down';
      else if (y < 0) direction = 'up';
      if (x > 0) direction = 'right';
      else if (x < 0) direction = 'left';

      if (direction) {
        this.lastDirection = direction;
        eventBus.emit('joystick-move', { direction });
      }
    },
    handleKeyPress(event) {
      const directions = {
        ArrowUp: { x: 50, y: 0 },    // Top center
        ArrowDown: { x: 50, y: 100 }, // Bottom center
        ArrowLeft: { x: 0, y: 50 },  // Center left
        ArrowRight: { x: 100, y: 50 }, // Center right
      };

      if (event.key in directions && !this.fireEventInterval) {
        const { x, y } = directions[event.key];

        // Update knob position to edge based on key pressed
        this.knobPosition.x = x;
        this.knobPosition.y = y;

        // Start continuous event firing
        this.startContinuousEvents(x - 50, y - 50);
      }
    },
    startContinuousEvents(x, y) {
      // Emit the direction immediately
      this.emitDirection(x, y);

      // Start interval for continuous events
      this.fireEventInterval = setInterval(() => {
        this.emitDirection(x, y);
      }, 200); // Adjust interval as needed
    },
    stopContinuousEvents() {
      // Clear the interval and reset knob position
      clearInterval(this.fireEventInterval);
      this.fireEventInterval = null;

      // Reset knob to center
      this.knobPosition = { x: 50, y: 50 };
      this.lastDirection = '';
    },
    startDrag(event) {
      this.dragging = true;
      const rect = this.$refs.joystickBase.getBoundingClientRect();
      this.center = { x: rect.width / 2, y: rect.height / 2 };

      const x = event.clientX - rect.left - this.center.x;
      const y = event.clientY - rect.top - this.center.y;

      // Emit events while dragging
      this.startContinuousEvents(x, y);
    },
    drag(event) {
      if (!this.dragging) return;

      const rect = this.$refs.joystickBase.getBoundingClientRect();
      const x = event.clientX - rect.left - this.center.x;
      const y = event.clientY - rect.top - this.center.y;

      const distance = Math.sqrt(x ** 2 + y ** 2);
      if (distance > this.radius) {
        const scale = this.radius / distance;
        this.knobPosition.x = this.center.x + x * scale;
        this.knobPosition.y = this.center.y + y * scale;
      } else {
        this.knobPosition.x = this.center.x + x;
        this.knobPosition.y = this.center.y + y;
      }

      this.emitDirectionThrottled(this.knobPosition.x - this.center.x, this.knobPosition.y - this.center.y);
    },
    endDrag() {
      this.dragging = false;
      this.stopContinuousEvents();
    },
    handleTouchStart(event) {
      const touch = event.touches[0];
      this.startDrag({ clientX: touch.clientX, clientY: touch.clientY });
    },
    handleTouchMove(event) {
      const touch = event.touches[0];
      this.drag({ clientX: touch.clientX, clientY: touch.clientY });
    },
    handleTouchEnd() {
      this.endDrag();
    },
  },
};
</script>

<style scoped>
.joystick-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  outline: none;
}

.instructions {
  font-size: 14px;
  color: #666;
}

.joystick {
  position: relative;
  width: 100px;
  height: 100px;
}

.joystick-base {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: radial-gradient(circle, #cccccc, #999999);
  border-radius: 50%;
  border: 3px solid #666;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
}

.joystick-knob {
  position: absolute;
  width: 40px;
  height: 40px;
  background: radial-gradient(circle, #555, #333);
  border-radius: 50%;
  border: 2px solid #111;
  transform: translate(-50%, -50%);
  cursor: grab;
  left: 50%;
  top: 50%;
  box-shadow: 0 3px 10px rgba(0, 0, 0, 0.2);
}
</style>

// src/components/map/Joystick.tsx
'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { throttle } from 'lodash';
import eventBus from '@/eventBus';

export default function Joystick() {
    const [knobPosition, setKnobPosition] = useState({ x: 50, y: 50 });
    const [dragging, setDragging] = useState(false);
    const joystickBaseRef = useRef<HTMLDivElement>(null);
    const centerRef = useRef({ x: 50, y: 50 });
    const radius = 50;
    const fireEventIntervalRef = useRef<NodeJS.Timeout | null>(null);
    const lastDirectionRef = useRef('');

    const emitDirection = useCallback((x: number, y: number) => {
        let direction = '';

        if (y > 0) direction = 'down';
        else if (y < 0) direction = 'up';
        if (x > 0) direction = 'right';
        else if (x < 0) direction = 'left';

        if (direction) {
            // Always emit if we are moving, MapService handles continuous movement
            eventBus.emit('map-move', direction);
        }
    }, []);

    const emitDirectionThrottled = useCallback(throttle((x: number, y: number) => {
        emitDirection(x, y);
    }, 50), [emitDirection]); // Faster throttle for smoother movement

    const startContinuousEvents = useCallback((x: number, y: number) => {
        emitDirection(x, y);
        if (fireEventIntervalRef.current) clearInterval(fireEventIntervalRef.current);
        fireEventIntervalRef.current = setInterval(() => {
            emitDirection(x, y);
        }, 50); // Faster interval
    }, [emitDirection]);

    const stopContinuousEvents = useCallback(() => {
        if (fireEventIntervalRef.current) {
            clearInterval(fireEventIntervalRef.current);
            fireEventIntervalRef.current = null;
        }
        setKnobPosition({ x: 50, y: 50 });
        lastDirectionRef.current = '';
    }, []);

    const handleKeyPress = useCallback((event: KeyboardEvent) => {
        const directions: Record<string, { x: number; y: number }> = {
            ArrowUp: { x: 50, y: 0 },
            ArrowDown: { x: 50, y: 100 },
            ArrowLeft: { x: 0, y: 50 },
            ArrowRight: { x: 100, y: 50 },
        };

        if (event.key in directions && !fireEventIntervalRef.current) {
            const { x, y } = directions[event.key];
            setKnobPosition({ x, y });
            startContinuousEvents(x - 50, y - 50);
        }
    }, [startContinuousEvents]);

    const handleKeyUp = useCallback(() => {
        stopContinuousEvents();
    }, [stopContinuousEvents]);

    useEffect(() => {
        window.addEventListener('keydown', handleKeyPress);
        window.addEventListener('keyup', handleKeyUp);
        return () => {
            window.removeEventListener('keydown', handleKeyPress);
            window.removeEventListener('keyup', handleKeyUp);
            stopContinuousEvents();
        };
    }, [handleKeyPress, handleKeyUp, stopContinuousEvents]);

    const startDrag = (clientX: number, clientY: number) => {
        setDragging(true);
        if (joystickBaseRef.current) {
            const rect = joystickBaseRef.current.getBoundingClientRect();
            centerRef.current = { x: rect.width / 2, y: rect.height / 2 };
            const x = clientX - rect.left - centerRef.current.x;
            const y = clientY - rect.top - centerRef.current.y;
            startContinuousEvents(x, y);
        }
    };

    const drag = (clientX: number, clientY: number) => {
        if (!dragging || !joystickBaseRef.current) return;

        const rect = joystickBaseRef.current.getBoundingClientRect();
        const x = clientX - rect.left - centerRef.current.x;
        const y = clientY - rect.top - centerRef.current.y;

        const distance = Math.sqrt(x ** 2 + y ** 2);
        let newX = x;
        let newY = y;

        if (distance > radius) {
            const scale = radius / distance;
            newX = x * scale;
            newY = y * scale;
        }

        setKnobPosition({
            x: centerRef.current.x + newX,
            y: centerRef.current.y + newY,
        });

        emitDirectionThrottled(newX, newY);
    };

    const endDrag = () => {
        setDragging(false);
        stopContinuousEvents();
    };

    return (
        <div className="flex flex-col items-center gap-[10px] outline-none">
            <h2 className="text-xl font-bold">Map Controls</h2>
            <p className="text-[14px] text-[#666]">Use the arrow keys, touch, or drag the joystick to move the map.</p>
            <br />
            <div
                className="relative w-[100px] h-[100px]"
                onTouchStart={(e) => startDrag(e.touches[0].clientX, e.touches[0].clientY)}
                onTouchMove={(e) => drag(e.touches[0].clientX, e.touches[0].clientY)}
                onTouchEnd={endDrag}
                onMouseDown={(e) => startDrag(e.clientX, e.clientY)}
                onMouseMove={(e) => drag(e.clientX, e.clientY)}
                onMouseUp={endDrag}
                onMouseLeave={endDrag}
            >
                <div
                    ref={joystickBaseRef}
                    className="absolute top-0 left-0 w-full h-full rounded-full border-[3px] border-[#666] shadow-[0_5px_15px_rgba(0,0,0,0.2)]"
                    style={{ background: 'radial-gradient(circle, #cccccc, #999999)' }}
                >
                    <div
                        className="absolute w-[40px] h-[40px] rounded-full border-[2px] border-[#111] cursor-grab shadow-[0_3px_10px_rgba(0,0,0,0.2)]"
                        style={{
                            background: 'radial-gradient(circle, #555, #333)',
                            left: `${knobPosition.x}px`,
                            top: `${knobPosition.y}px`,
                            transform: 'translate(-50%, -50%)',
                        }}
                    ></div>
                </div>
            </div>
        </div>
    );
}
